server:
  port: 9003
spring:
  application:
    name: spingcloud-stream-consumer1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        my_msg: ###指定 管道名称
          #指定该应用实例属于 stream 消费组
          group: stream